### ISSUE TITLE
Adding GregTech Modern support?

### ISSUE THREAD

**Issue by 3453890470** [Porting-Dead-Mods/DuraDisplay#3]

**Comment by Leclowndu93150** [comment]
We tried, we failed, we'll retry today

**Comment by 3453890470** [comment]
iss has been sent to GregTech Modern

**Comment by Leclowndu93150** [comment]
1.21

**Comment by 3453890470** [comment]
Oh the good！

**Comment by Leclowndu93150** [comment]
i'm waiting for the next GT update to push, as my mate changed some GT code to fit how our mod works

**Comment by Thepigcat76** [comment]
GT compat is added :)
