### ISSUE TITLE
[Bug] Durability not shown.

### ISSUE THREAD

**Issue by Kevin-Marsh** [Porting-Dead-Mods/DuraDisplay#5]
Durability is not being shown on tools. This was mostly tested with vanilla tools. The tools always show as unbroken until they break. RF from modded tools shows nicely.

Neoforge: 21.0.51

**Comment by Leclowndu93150** [comment]
https://www.curseforge.com/minecraft/mc-mods/durability-display/files/5501460
have you installed this version ?
